### ISSUE TITLE
Use cases

### ISSUE THREAD

**Issue by jlursenbach** [jlursenbach/CPSC-362-summer-group#6]

**Comment by jlursenbach** [comment]
Format:
- ***ID*:**
- ***Name*:**
- Description: (optional some times)
- ***Primary Actor*:**
- Preconditions:
- Postconditions:
- ***Main Success Scenario (flow)*:**

**Comment by jlursenbach** [comment]
![image](https://user-images.githubusercontent.com/61986930/177900670-df1a58fd-9072-46ea-a717-4a6ae4c40729.png)

**Comment by jlursenbach** [comment]
USER:

Generate a list of stocks
Sort the list
Filter the list
     - we need to decide what to sort & filter by 
Select specific stock from the list
View stock data 
	- the product that the company sells
	- product popularity (consumer needs)
	- stock price trend chart 
	       (chart should show company performance up to 5 years)
	- opening and closing prices
	- PE ratio (price per earning)
	- PS ratio (price per share)
	- company cash reserve
	- company debt
	- company management effectiveness data 
			(return on asset and return on equity data)

DEVELOPER:
	- scrape a list of stocks from - somewhere - (Yahoo finance?)
	- grab stock data from - somewhere - (Yahoo finance?)
	     - is there a REST API for this?
	     - https://algotrading101.com/learn/yahoo-finance-api-guide/
	- put the data into .json or py-dict
	- figure out an interactive display system for stock data	
		- display info from a py-dict or .json
		- create a number of frames
		- display info in a respective frame
		- scroll, filter, select

**Comment by jlursenbach** [comment]
{case_id : 
{Name:
{Description: (optional some times)
{Primary Actor:
{Preconditions:
{Postconditions:
{Main Success Scenario (flow):   [ 1,2,3 ] }}

**Comment by goodpointy** [comment]
im going to work on the use case for viewing stock data

**Comment by jlursenbach** [comment]
I'm going to be working on create a list of stocks

**Comment by goodpointy** [comment]
I'm going to do the developer case and story for grabbing stock data from yahoo finance

**Comment by ziyanggreg** [comment]
I'm going to work on sorting and filtering the list of stocks

**Comment by jlursenbach** [comment]
Go ahead and check the box once  The Use Case and User Story for each item: is complete:

User Requirements:
- [x] Generate a list of stocks
- [ ] Sort the list
- [ ] Filter the list
- [ ] Select specific stock from the list
- [x] View stock data 

Developer Requirements:
- [ ] scrape a list of stocks from - somewhere - (Yahoo finance?)
- [ ] grab stock data from - somewhere - (Yahoo finance?)
- [ ] put the data into .json or py-dict
- [ ] figure out an interactive display system for stock data

**Comment by jlursenbach** [comment]
Go ahead and check the box once  The Use Case and User Story for each item: is complete:

User Requirements:
- [x] Generate a list of stocks
- [ ] Sort the list
- [ ] Filter the list
- [ ] Select specific stock from the list
- [x] View stock data 

Developer Requirements:
- [ ] scrape a list of stocks from - somewhere - (Yahoo finance?)
- [ ] grab stock data from - somewhere - (Yahoo finance?)
- [ ] put the data into .json or py-dict

**Comment by thomastran321** [comment]
I'll work on grabbing stock and interactive display system for stock data.

**Comment by jlursenbach** [comment]
This is a sub-issue of assignment 1 (#4) 
closed as the user stories issue is complete
